// ─────────────────────────────────────────
// data.js — Category & food data
// ─────────────────────────────────────────

const CATS = [
  {
    id: "fruits", name: "Fruits", emoji: "🍎", desc: "16 foods",
    foods: [
      { n: "Apple (medium)", e: "🍎", k: 95 },
      { n: "Banana (medium)", e: "🍌", k: 105 },
      { n: "Avocado (half)", e: "🥑", k: 160 },
      { n: "Strawberries 100g", e: "🍓", k: 32 },
      { n: "Mango (medium)", e: "🥭", k: 202 },
      { n: "Blueberries 1 cup", e: "🫐", k: 84 },
      { n: "Orange (medium)", e: "🍊", k: 62 },
      { n: "Grapes 1 cup", e: "🍇", k: 104 },
      { n: "Watermelon 2 cups", e: "🍉", k: 85 },
      { n: "Pineapple 1 cup", e: "🍍", k: 82 },
      { n: "Kiwi (medium)", e: "🥝", k: 61 },
      { n: "Peach (medium)", e: "🍑", k: 59 },
      { n: "Lemon (medium)", e: "🍋", k: 17 },
      { n: "Cherries 1 cup", e: "🍒", k: 87 },
      { n: "Papaya 1 cup", e: "🥭", k: 62 },
      { n: "Pomegranate seeds 100g", e: "🌹", k: 83 },
    ],
  },
  {
    id: "vegetables", name: "Vegetables", emoji: "🥦", desc: "14 foods",
    foods: [
      { n: "Broccoli 1 cup", e: "🥦", k: 55 },
      { n: "Spinach 100g raw", e: "🥬", k: 23 },
      { n: "Sweet potato medium", e: "🍠", k: 130 },
      { n: "Carrot medium", e: "🥕", k: 25 },
      { n: "Bell pepper red", e: "🫑", k: 31 },
      { n: "Tomato medium", e: "🍅", k: 22 },
      { n: "Cucumber medium", e: "🥒", k: 16 },
      { n: "Kale 100g", e: "🥬", k: 49 },
      { n: "Zucchini medium", e: "🥒", k: 33 },
      { n: "Beets 1 cup cooked", e: "🍠", k: 75 },
      { n: "Onion medium", e: "🧅", k: 44 },
      { n: "Garlic 1 clove", e: "🧄", k: 4 },
      { n: "Celery 1 cup", e: "🌿", k: 14 },
      { n: "Mushrooms 1 cup", e: "🍄", k: 21 },
    ],
  },
  {
    id: "proteins", name: "Proteins", emoji: "🍗", desc: "12 foods",
    foods: [
      { n: "Chicken breast 100g grilled", e: "🍗", k: 165 },
      { n: "Salmon fillet 100g", e: "🐟", k: 208 },
      { n: "Eggs 2 large", e: "🥚", k: 156 },
      { n: "Tuna canned 100g", e: "🐟", k: 116 },
      { n: "Beef sirloin 100g", e: "🥩", k: 207 },
      { n: "Tofu firm 100g", e: "🟡", k: 76 },
      { n: "Shrimp 100g cooked", e: "🦐", k: 99 },
      { n: "Turkey breast 100g", e: "🦃", k: 135 },
      { n: "Lamb chop 100g", e: "🥩", k: 258 },
      { n: "Pork tenderloin 100g", e: "🥩", k: 143 },
      { n: "Tempeh 100g", e: "🌰", k: 193 },
      { n: "Edamame 1 cup", e: "🫘", k: 188 },
    ],
  },
  {
    id: "grains", name: "Grains", emoji: "🍚", desc: "10 foods",
    foods: [
      { n: "Brown rice 1 cup cooked", e: "🍚", k: 216 },
      { n: "Oats 100g dry", e: "🥣", k: 389 },
      { n: "Quinoa 1 cup cooked", e: "🌾", k: 222 },
      { n: "Whole wheat bread 2 slices", e: "🍞", k: 160 },
      { n: "Pasta 1 cup cooked", e: "🍝", k: 220 },
      { n: "White rice 1 cup cooked", e: "🍚", k: 242 },
      { n: "Barley 1 cup cooked", e: "🌾", k: 193 },
      { n: "Buckwheat 1 cup cooked", e: "🌾", k: 155 },
      { n: "Corn tortilla 2 medium", e: "🫓", k: 100 },
      { n: "Granola 50g", e: "🥣", k: 224 },
    ],
  },
  {
    id: "dairy", name: "Dairy", emoji: "🥛", desc: "10 foods",
    foods: [
      { n: "Greek yogurt full fat 100g", e: "🥛", k: 100 },
      { n: "Whole milk 1 cup", e: "🥛", k: 149 },
      { n: "Cheddar cheese 30g", e: "🧀", k: 120 },
      { n: "Cottage cheese 100g", e: "🥛", k: 98 },
      { n: "Mozzarella 30g", e: "🧀", k: 85 },
      { n: "Butter 1 tbsp", e: "🧈", k: 102 },
      { n: "Cream cheese 2 tbsp", e: "🧀", k: 101 },
      { n: "Skim milk 1 cup", e: "🥛", k: 83 },
      { n: "Parmesan 30g", e: "🧀", k: 122 },
      { n: "Kefir 1 cup", e: "🥛", k: 110 },
    ],
  },
  {
    id: "nuts", name: "Nuts & Seeds", emoji: "🥜", desc: "10 foods",
    foods: [
      { n: "Almonds 30g", e: "🌰", k: 170 },
      { n: "Walnuts 30g", e: "🌰", k: 196 },
      { n: "Peanut butter 2 tbsp", e: "🥜", k: 190 },
      { n: "Cashews 30g", e: "🌰", k: 157 },
      { n: "Sunflower seeds 30g", e: "🌻", k: 175 },
      { n: "Chia seeds 2 tbsp", e: "⚫", k: 138 },
      { n: "Flaxseeds 2 tbsp", e: "🌾", k: 110 },
      { n: "Pistachios 30g", e: "🌿", k: 159 },
      { n: "Hemp seeds 3 tbsp", e: "🌿", k: 166 },
      { n: "Pumpkin seeds 30g", e: "🎃", k: 163 },
    ],
  },
  {
    id: "legumes", name: "Legumes", emoji: "🫘", desc: "8 foods",
    foods: [
      { n: "Black beans 1 cup cooked", e: "🫘", k: 227 },
      { n: "Lentils 1 cup cooked", e: "🫘", k: 230 },
      { n: "Chickpeas 1 cup cooked", e: "🫘", k: 269 },
      { n: "Kidney beans 1 cup cooked", e: "🫘", k: 225 },
      { n: "Green peas 1 cup", e: "🟢", k: 118 },
      { n: "Soybeans 1 cup cooked", e: "🫘", k: 298 },
      { n: "Navy beans 1 cup cooked", e: "🫘", k: 255 },
      { n: "Pinto beans 1 cup cooked", e: "🫘", k: 245 },
    ],
  },
];
